# Generated by Django 2.2.5 on 2019-11-05 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeModel',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('phono', models.IntegerField()),
                ('email', models.EmailField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('photo', models.ImageField(upload_to='images')),
                ('idno', models.IntegerField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=30)),
            ],
        ),
    ]
