# Generated by Django 2.2.5 on 2019-11-05 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegemodel',
            name='email',
            field=models.EmailField(max_length=40, unique=True),
        ),
    ]
